# Cloudflare Api

### 获取账号信息

POST {{$dotenv TDP_API_BASE}}/cloudflare/3
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Path": "/user"
}

### 获取域名列表

POST {{$dotenv TDP_API_BASE}}/cloudflare/3
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Path": "/zones"
}

### 获取域名列表 - 根据条件筛选

POST {{$dotenv TDP_API_BASE}}/cloudflare/3
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Path": "/zones",
    "Query": "name=anrip.com"
}

### 获取域名详情

POST {{$dotenv TDP_API_BASE}}/cloudflare/3
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Path": "/zones/3bf29adb3736dda1506aca5084a71dfc"
}

###
