# Native Machine Api

### 获取主机

GET {{$dotenv TDP_API_BASE}}/machine/list
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{}

### 删除主机

POST {{$dotenv TDP_API_BASE}}/machine/delete
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Id": 2
}
