# Native Passport Api

### 注册账号

POST {{$dotenv TDP_API_BASE}}/passport/register
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Username":"{{$dotenv TDP_USERNAME}}",
    "Password": "{{$dotenv TDP_PASSWORD}}",
    "Email": "admin@tdp.icu"
}

### 登录账号

POST {{$dotenv TDP_API_BASE}}/passport/login
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Username":"{{$dotenv TDP_USERNAME}}",
    "Password": "{{$dotenv TDP_PASSWORD}}"
}

### 修改资料

POST {{$dotenv TDP_API_BASE}}/passport/profile/update
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Password": "{{$dotenv TDP_PASSWORD}}",
    "OldPassword": "{{$dotenv TDP_PASSWORD}}",
    "Email": "admin2@tdp.icu",
    "Description": "不可能！我的代码怎么可能会有Bug！"
}
