# Qcloud Lighthouse Api

### 获取地域

POST {{$dotenv TDP_API_BASE}}/qcloud/lighthouse/2020-03-24/DescribeRegions
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

### 获取地域实例

POST {{$dotenv TDP_API_BASE}}/qcloud/lighthouse/2020-03-24/DescribeInstances/ap-guangzhou
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

### 获取实例流量包

POST {{$dotenv TDP_API_BASE}}/qcloud/lighthouse/2020-03-24/DescribeInstancesTrafficPackages/ap-guangzhou
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}
