# Qcloud Lighthouse Api

### 获取地域

POST {{$dotenv API_BASE}}/qcloud/lighthouse/2020-03-24/DescribeRegions
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}

### 获取地域实例

POST {{$dotenv API_BASE}}/qcloud/lighthouse/2020-03-24/DescribeInstances/ap-guangzhou
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}

### 获取实例流量包

POST {{$dotenv API_BASE}}/qcloud/lighthouse/2020-03-24/DescribeInstancesTrafficPackages/ap-guangzhou
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}
