# Qcloud Api

### 获取账号信息

POST {{$dotenv TDP_API_BASE}}/qcloud/1
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Service": "cam",
    "Action": "GetAccountSummary",
    "Version": "2019-01-16",
    "Payload": {}
}

###
