# Qcloud Lighthouse Api

### 获取监控数据

POST {{$dotenv TDP_API_BASE}}/qcloud/monitor/2018-07-24/GetMonitorData/ap-guangzhou
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Namespace": "QCE/LIGHTHOUSE",
    "MetricName": "LighthouseOuttraffic",
    "Instances": [
        {
            "Dimensions": [
                {
                    "Name": "InstanceId",
                    "Value": "lhins-mdwnpgap"
                }
            ]
        }
    ],
    "Period": 300,
    "StartTime": "2022-06-20 00:00:00",
    "EndTime": "2022-06-30 23:59:59"
}
