# Local TAT Api

### 列表

GET {{$dotenv API_BASE}}/tat/script
Authorization: {{$dotenv AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv ORIGIN}}


### 查看一条

GET {{$dotenv API_BASE}}/tat/script/1
Authorization: {{$dotenv AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv ORIGIN}}

### 添加

POST {{$dotenv API_BASE}}/tat/script
Authorization: {{$dotenv AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv ORIGIN}}

{
    "Name":  "name",
    "Description": "description",
    "Content":  "content"
}

### 更新

PATCH {{$dotenv API_BASE}}/tat/script/1
Authorization: {{$dotenv AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv ORIGIN}}

{
    "Id": 1,
    "Name":  "name222",
    "Description": "description",
    "Content":  "content"
}

### 删除

DELETE {{$dotenv API_BASE}}/tat/script/1
Authorization: {{$dotenv AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv ORIGIN}}
