# Local TAT Api

### 列表

GET {{$dotenv TDP_API_BASE}}/tat/script
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}


### 查看一条

GET {{$dotenv TDP_API_BASE}}/tat/script/1
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

### 添加

POST {{$dotenv TDP_API_BASE}}/tat/script
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Name":  "name",
    "Description": "description",
    "Content":  "content"
}

### 更新

PATCH {{$dotenv TDP_API_BASE}}/tat/script/1
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Id": 1,
    "Name":  "name222",
    "Description": "description",
    "Content":  "content"
}

### 删除

DELETE {{$dotenv TDP_API_BASE}}/tat/script/1
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}
