# Tencent Cloud Api

### 获取账号信息

POST {{$dotenv TDP_API_BASE}}/tencent/1
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Service": "cam",
    "Action": "GetAccountSummary",
    "Version": "2019-01-16",
    "Payload": {}
}

### 获取实例信息

POST {{$dotenv TDP_API_BASE}}/tencent/1
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Service": "cvm",
    "Version": "2017-03-12",
    "Action": "DescribeInstances",
    "Region": "ap-shanghai",
    "Payload": {
        "Limit": 100
    }
}
