# Local User Api

### 注册账号

POST {{$dotenv API_BASE}}/user/register
Origin: {{$dotenv ORIGIN}}
Content-Type: application/json

{
    "Username":"{{$dotenv USERNAME}}",
    "Password": "{{$dotenv PASSWORD}}"
}

### 登录账号

POST {{$dotenv API_BASE}}/user/login
Origin: {{$dotenv ORIGIN}}
Content-Type: application/json

{
    "Username":"{{$dotenv USERNAME}}",
    "Password": "{{$dotenv PASSWORD}}"
}

### 修改资料

PATCH {{$dotenv API_BASE}}/user/info
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}
Content-Type: application/json

{
    "Description": "不可能！我的代码怎么可能会有Bug！"
}

### 修改密码

PATCH {{$dotenv API_BASE}}/user/PASSWORD
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}
Content-Type: application/json

{
    "OldPassword": "{{$dotenv PASSWORD}}",
    "NewPassword": "{{$dotenv PASSWORD}}"
}
