# Local Vendor Api

### 获取厂商

GET {{$dotenv baseapi}}/vendor
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}

### 添加厂商

POST {{$dotenv baseapi}}/vendor
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "SecretId":  "{{$dotenv secret_id}}",
    "SecretKey": "{{$dotenv secret_key}}",
	"Provider":  "qcloud",
    "Description":  "也没所谓"
}

### 删除厂商

DELETE {{$dotenv baseapi}}/vendor/2
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}
