# Native Vendor Api

### 获取厂商

POST {{$dotenv TDP_API_BASE}}/vendor/list
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "provider": "cloudflare"
}

### 添加厂商

POST {{$dotenv TDP_API_BASE}}/vendor/create
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "SecretId":  "{{$dotenv TDP_SECRET_ID}}",
    "SecretKey": "{{$dotenv TDP_SECRET_KEY}}",
	"Provider":  "{{$dotenv TDP_SECRET_VENDOR}}",
    "Description":  "也没所谓"
}

### 删除厂商

POST {{$dotenv TDP_API_BASE}}/vendor/delete
Authorization: {{$dotenv TDP_AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv TDP_ORIGIN}}

{
    "Id": 2
}
