# Local Vendor Api

### 获取厂商

GET {{$dotenv API_BASE}}/vendor
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}

### 添加厂商

POST {{$dotenv API_BASE}}/vendor
Authorization: {{$dotenv AUTHORIZATION}}
Content-Type: application/json
Origin: {{$dotenv ORIGIN}}

{
    "SecretId":  "{{$dotenv SECRET_ID}}",
    "SecretKey": "{{$dotenv SECRET_KEY}}",
	"Provider":  "qcloud",
    "Description":  "也没所谓"
}

### 删除厂商

DELETE {{$dotenv API_BASE}}/vendor/2
Authorization: {{$dotenv AUTHORIZATION}}
Origin: {{$dotenv ORIGIN}}
