# Lighthouse Api

### 获取所有区域和实例

GET {{$dotenv baseapi}}/cloud/lighthouse/describeRegionsInstances
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}

### 查看实例流量包详情

GET {{$dotenv baseapi}}/cloud/lighthouse/describeInstancesTrafficPackages/ap-guangzhou
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}
