# Local Secret Api

### 获取密钥

GET {{$dotenv baseapi}}/secret
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}

### 添加密钥

POST {{$dotenv baseapi}}/secret
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "secretId":  "{{$dotenv secret_id}}",
    "secretKey": "{{$dotenv secret_key}}",
    "description":  "也没所谓"
}

### 删除密钥

DELETE {{$dotenv baseapi}}/secret/2
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}
