# Local TAT Api

### 列表

GET {{$dotenv baseapi}}/tat
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}


### 查看一条

GET {{$dotenv baseapi}}/tat/1
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

### 添加

POST {{$dotenv baseapi}}/tat
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "name":  "name",
    "description": "description",
    "content":  "content"
}

### 更新

PATCH {{$dotenv baseapi}}/tat/1
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "id": 1,
    "name":  "name222",
    "description": "description",
    "content":  "content"
}

### 删除

DELETE {{$dotenv baseapi}}/tat/1
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}
