# Dnspod Api

@origin = http://localhost:7800
@baseapi = http://localhost:7800/api

### 注册账号

POST {{baseapi}}/user/register
Origin: {{origin}}
Content-Type: application/json

{
    "username":"admin",
    "password": "admin"
}

### 登录账号

POST {{baseapi}}/user/login
Origin: {{origin}}
Content-Type: application/json

{
    "username":"admin",
    "password": "admin"
}
