# User Api

### 注册账号

POST {{$dotenv baseapi}}/local/user/register
Origin: {{$dotenv origin}}
Content-Type: application/json

{
    "username":"{{$dotenv username}}",
    "password": "{{$dotenv password}}"
}

### 登录账号

POST {{$dotenv baseapi}}/local/member/login
Origin: {{$dotenv origin}}
Content-Type: application/json

{
    "username":"{{$dotenv username}}",
    "password": "{{$dotenv password}}"
}

### 修改资料

PATCH {{$dotenv baseapi}}/local/user/info
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}
Content-Type: application/json

{
    "description": "不可能！我的代码怎么可能会有bug！"
}

### 修改密码

PATCH {{$dotenv baseapi}}/local/user/password
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}
Content-Type: application/json

{
    "oldPassword": "{{$dotenv password}}",
    "newPassword": "{{$dotenv password}}"
}

### 添加密钥

POST {{$dotenv baseapi}}/local/user/secret
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "secretId":  "{{$dotenv secret_id}}",
    "secretKey": "{{$dotenv secret_key}}",
    "description":  "也没所谓"
}

### 获取密钥

GET {{$dotenv baseapi}}/local/user/secret
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}

### 删除密钥

DELETE {{$dotenv baseapi}}/local/user/secret/2
Authorization: {{$dotenv authorization}}
Origin: {{$dotenv origin}}


### 添加TAT

POST {{$dotenv baseapi}}/local/tat/create
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "name":  "name",
    "description": "description",
    "content":  "content"
}

### TAT list

GET {{$dotenv baseapi}}/local/tat/list
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}


### TAT Info

GET {{$dotenv baseapi}}/local/tat/info/1
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

### 跟新TAT

POST {{$dotenv baseapi}}/local/tat/update
Authorization: {{$dotenv authorization}}
Content-Type: application/json
Origin: {{$dotenv origin}}

{
    "id": 1,
    "name":  "name222",
    "description": "description",
    "content":  "content"
}
