# User Api

### 注册账号

POST {{$dotenv baseapi}}/local/user/register
Origin: {{$dotenv origin}}
Content-Type: application/json

{
    "username":"admin",
    "password": "admin"
}

### 登录账号

POST {{$dotenv baseapi}}/local/user/login
Origin: {{$dotenv origin}}
Content-Type: application/json

{
    "username":"admin",
    "password": "admin"
}
