#!/bin/sh
#

mkdir -p /etc/tdp-cloud
mkdir -p /var/lib/tdp-cloud
mkdir -p /var/log/tdp-cloud

yml=/etc/tdp-cloud/server.yml

[ -f $yml ] || cat <<EOF >$yml
dataset:
    dir: /var/lib/tdp-cloud
logger:
    dir: /var/log/tdp-cloud
    level: info
server:
    listen: :7800
EOF

exec tdp-cloud server -c $yml
