#!/bin/sh
#

set -e
set -o noglob

# --- global env ---

TDP_DOWNLOAD_URL=http://tdp.icu/build/tdp-cloud-linux-amd64.gz

TDP_EXEC_FILE=/usr/local/bin/tdp-cloud

if [ ! $TDP_EXEC_ARGS ]; then
    echo "[ERROR] Missing environment variable \$TDP_EXEC_ARGS"
    exit 1
fi

# --- download binary ---

download_binary() {
    if type curl >/dev/null 2>&1; then
        curl -sfL $TDP_DOWNLOAD_URL | gunzip > $TDP_EXEC_FILE
        return
    fi

    if type wget >/dev/null 2>&1; then
        wget -qO- $TDP_DOWNLOAD_URL | gunzip > $TDP_EXEC_FILE
        return
    fi

    if [ ! -e $TDP_EXEC_FILE ]; then
        fatal "[ERROR] Can't download ${TDP_DOWNLOAD_URL}"
        exit 1
    fi
}

# --- service helper ---

service_install() {
    download_binary
    chmod +x $TDP_EXEC_FILE

    $TDP_EXEC_FILE service --install worker - $TDP_EXEC_ARGS
    mkdir -p /var/lib/tdp-cloud
    mkdir -p /var/log/tdp-cloud

    service tpd-worker start
}

service_uninstall() {
    service tpd-worker stop

    tdp-cloud service --uninstall worker
    rm -rf `which tdp-cloud`
    rm -rf /var/*/tdp-cloud*
}

# ---

service_install
