#!/bin/sh
#

set -e
set -o noglob

# --- global env ---

if [ -z "$TDP_EXEC" ]; then
    TDP_EXEC=/usr/local/bin/tdp-cloud
fi

if [ -z "$TDP_REMOTE_URL" ]; then
    echo "[ERROR] Missing environment variable \$TDP_REMOTE_URL"
    exit 1
fi

if [ -z "$TDP_PACKAGE" ]; then
    TDP_PACKAGE=http://tdp.icu/build/tdp-cloud-linux-amd64.gz
fi

# --- download binary ---

if type curl >/dev/null 2>&1; then
    curl -sfL $TDP_PACKAGE | gunzip > $TDP_EXEC
elif type wget >/dev/null 2>&1; then
    wget -qO- $TDP_PACKAGE | gunzip > $TDP_EXEC
fi

if [ ! -e $TDP_EXEC ]; then
    echo "[ERROR] Can't download ${TDP_PACKAGE}"
    exit 1
fi

# --- create service ---

chmod +x $TDP_EXEC
mkdir -p /etc/tdp-cloud
mkdir -p /var/lib/tdp-cloud
mkdir -p /var/log/tdp-cloud

cat <<EOF >/etc/tdp-cloud/config.yml
worker:
    remote: $TDP_REMOTE_URL
EOF

$TDP_EXEC worker -s install -c /etc/tdp-cloud/config.yml
$TDP_EXEC worker -s start

# --- create uninstall script ---

cat <<EOF >$TDP_EXEC-uninstall
#!/bin/sh
$TDP_EXEC worker -s stop
$TDP_EXEC worker -s uninstall
rm -rf /var/*/tdp-cloud*
rm -rf /etc/tdp-cloud*
rm -rf $TDP_EXEC*
EOF

chmod +x $TDP_EXEC-uninstall
