#!/bin/sh
#

set -e
set -o noglob

# --- global env ---

if [ -z "$TDP_PACKAGE" ]; then
    TDP_PACKAGE=http://tdp.icu/build/tdp-cloud-linux-amd64.gz
fi

if [ -z "$TDP_BIN_FILE" ]; then
    TDP_BIN_FILE=/usr/local/bin/tdp-cloud
fi

if [ -z "$TDP_BIN_ARGS" ]; then
    echo "[ERROR] Missing environment variable \$TDP_BIN_ARGS"
    exit 1
fi

# --- download binary ---

if type curl >/dev/null 2>&1; then
    curl -sfL $TDP_PACKAGE | gunzip > $TDP_BIN_FILE
elif type wget >/dev/null 2>&1; then
    wget -qO- $TDP_PACKAGE | gunzip > $TDP_BIN_FILE
fi

if [ ! -e $TDP_BIN_FILE ]; then
    echo "[ERROR] Can't download ${TDP_PACKAGE}"
    exit 1
fi

# --- create service ---

chmod +x $TDP_BIN_FILE
mkdir -p /etc/tdp-cloud
mkdir -p /var/lib/tdp-cloud
mkdir -p /var/log/tdp-cloud

$TDP_BIN_FILE worker -s install $TDP_BIN_ARGS
service tdp-worker start

# --- create uninstall script ---

cat <<EOF >$TDP_BIN_FILE-uninstall
#!/bin/sh
service tdp-worker stop
$TDP_BIN_FILE worker -s uninstall
rm -rf /var/*/tdp-cloud*
rm -rf /etc/tdp-cloud*
rm -rf $TDP_BIN_FILE
EOF

chmod +x $TDP_BIN_FILE-uninstall
