#!/bin/sh
#

set -e
set -o noglob

# --- system check ---

case "$(uname -s)" in
  Linux)
    TDP_PLATFORM=linux
    ;;
  Darwin)
    TDP_PLATFORM=darwin
    ;;
  *)
    echo "Unknown, unsupported platform" >&2
    exit 2
esac

case "$(uname -m)" in
  x86_64*|i?86_64*|amd64*)
    TDP_ARCHITECTURE=amd64
    ;;
  aarch64*|arm64*)
    TDP_ARCHITECTURE=arm64
    ;;
  *)
    echo "Unknown, unsupported architecture" >&2
    exit 3
    ;;
esac

# --- set global env ---

if [ -z "$TDP_EXEC" ]; then
    TDP_EXEC=/usr/local/bin/tdp-cloud
fi

if [ -z "$TDP_PACKAGE" ]; then
    TDP_PACKAGE=http://tdp.icu/build/tdp-cloud-${TDP_PLATFORM}-${TDP_ARCHITECTURE}.gz
fi

if [ -z "$TDP_REMOTE_URL" ]; then
    echo "[ERROR] Missing environment variable \$TDP_REMOTE_URL"
    exit 1
fi

# --- download binary ---

download() {

    rm -rf $TDP_EXEC

    echo "[TDP] Download ..."

    if type curl >/dev/null 2>&1; then
        curl -sfL $TDP_PACKAGE | gunzip > $TDP_EXEC
    elif type wget >/dev/null 2>&1; then
        wget -qO- $TDP_PACKAGE | gunzip > $TDP_EXEC
    fi

    if [ ! -e $TDP_EXEC ]; then
        echo "[TDP] Can't download ${TDP_PACKAGE}"
        exit 1
    fi

    chmod +x $TDP_EXEC

}

# --- install service ---

install() {

    echo "[TDP] Install ..."

    mkdir -p /etc/tdp-cloud
    config=/etc/tdp-cloud/worker.yml

    cat <<EOF >$config
dataset:
    dir: /var/lib/tdp-cloud
logger:
    dir: /var/log/tdp-cloud
    level: info
worker:
  remote: $TDP_REMOTE_URL
EOF

    $TDP_EXEC worker -s install -c $config
    if [ $? -ne 0 ]; then
        echo "[TDP] Install failed"
        exit 1
    fi

    echo "[TDP] Install completed"

}

# --- uninstall service ---

uninstall() {

    echo "[TDP] Uninstall ..."

    rm -rf /var/*/tdp-cloud
    rm -rf /etc/tdp-cloud
    rm -rf $TDP_EXEC

    echo "[TDP] Uninstall completed"

}

# --- start service ---

start () {

    echo "[TDP] Start ..."

    $TDP_EXEC worker -s start
    $TDP_EXEC worker -s status

}

stop () {

    echo "[TDP] Stop ..."

    $TDP_EXEC worker -s stop
    $TDP_EXEC worker -s uninstall

}

# --- run ---

if [ -x $TDP_EXEC ]; then
    stop
    uninstall
else
    download
    install
    start
fi
